version: "3.8"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: evaluaciones_prueba
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/
volumes:
  html: {}